export const SET_CURRENT_SOAP_LABEL = 'SET_CURRENT_SOAP_LABEL';
export const ADD_SOAP_LABEL = 'ADD_SOAP_LABEL';
export const EDIT_CURRENT_SOAP_LABEL = 'EDIT_CURRENT_SOAP_LABEL';
export const DELETE_CURRENT_SOAP_LABEL = 'DELETE_CURRENT_SOAP_LABEL';
export const EDIT_SETTINGS = 'EDIT_SETTINGS';