export const SET_REDUCED_OILS_DATA = "SET_REDUCED_OILS_DATA";
export const EDIT_SETTINGS = "EDIT_SETTINGS";
export const SET_STEP = "SET_STEP";
// export const SAVE_SETTING_PROPERTY_SETTINGS = "SAVE_SETTING_PROPERTY_SETTINGS";
